#! /bin/bash



# launch daemons

sxhkd &
compton -b -i 0.4 --active-opacity 0.8

# bspwm settings

bspc monitor -d I II III IV

bspc config normal_border_color		"#231f1d"
bspc config active_border_color		"#6a5e4b"
bspc config focused_border_color 	"#6a5e4b"

bspc config presel_feedback_color	"#6a5e4b"

bspc config border_width	4
bspc config window_gap		64
bspc config top_padding		$((25 + 64))

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# launch aesthetic programs

$HOME/scripts/bar/lemonbar.sh | lemonbar -g $(($WIDTH - 64 - 64 - 4 - 4))x$((25 - 4))+64+64 -f "CtrlD:size=10" -f "Siji:size=10" -F "#d5dadc" -B "#231f1d" -r 4 -R "#6a5e4b" -a 16 | bash &
feh --bg-scale /home/frank/pictures/backgrounds/blur_dark.jpg
unclutter &
sleep 1
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -a bar)

