#! /bin/bash



# launch daemons

sxhkd &
compton -b -i 1 --active-opacity 1

# bspwm settings

bspc monitor -d I II III IV

bspc config normal_border_color		"#f5f5e2"
bspc config active_border_color		"#edb458"
bspc config focused_border_color 	"#edb458"

bspc config presel_feedback_color	"#edb458"

bspc config border_width	5
bspc config window_gap		40
bspc config top_padding		$((25 + 40))

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# launch aesthetic programs

$HOME/scripts/bar/lemonbar.sh | lemonbar -g $(($WIDTH - 40 - 40 - 5 - 5))x$((25 - 5))+40+40 -f "CtrlD:size=10" -f "Siji:size=10" -F "#2c2b27" -B "#f5f5e2" -r 5 -R "#f5f5e2" -a 16 | bash &
feh --bg-scale /home/frank/pictures/backgrounds/spray.jpg
unclutter &
sleep 1
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -a bar)

