#!/usr/bin/env bash

. "$HOME/themes/active_theme"

# launch daemons
[ -z $(pgrep sxhkd) ] && sxhkd &
[ -z $(pgrep compton) ] && picom -b \
    -i $THEME_OPACITY_INACTIVE --active-opacity $THEME_OPACITY_ACTIVE

# bspwm settings
bspc config normal_border_color		\#$THEME_BORDER_INACTIVE
bspc config active_border_color		\#$THEME_BORDER_ACTIVE
bspc config focused_border_color 	\#$THEME_BORDER_ACTIVE

bspc config presel_feedback_color	\#$THEME_HIGHLIGHT

bspc config border_width	        $THEME_BORDER_WIDTH
bspc config window_gap		        $THEME_WINDOW_GAP
if [ $THEME_BAR_MODE = always ]; then
    bspc config top_padding		    $(($THEME_BAR_HEIGHT + $THEME_WINDOW_GAP))
else
    bspc config top_padding		    0
fi

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a "lemonbar" layer=above
bspc rule -a "Zathura" state=tiled

# set up monitor
autorandr -c
bspc monitor focused -d $(seq 1 $THEME_N_WINDOWS)
export _JAVA_AWT_WM_NONREPARENTING=1

xsetroot -cursor_name left_ptr

# launch background programs
[ -z $(pgrep lemonbar) ] && lemonbar.sh &
feh --bg-scale $THEME_WALLPAPER
[ -z $(pgrep unclutter) ] && unclutter &
[ -z $(pgrep redshift) ] && redshift &
